print('--------------------------')
print('Dissecando uma variável')
v = input('Digite um algo: ')
print('O tipo primitivo desse valor? ', type(v))
print('Só tem espaço? ', v.isspace()) 
print('É um número? ', v.isnumeric())
print('É alfabético? ', v.isalpha())
print('É um alfanumérico? ', v.isalnum())
print('Está em minúsculas?', v.islower())
print('Está em maiúculas?', v.isupper())
print('Está capitalizada? ', v.istitle())
print('--------------------------')
